#!/usr/bin/env bash

# Run as sudo only
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Please, run as root"
    exit
fi

ORIGIN=$PWD

echo "Installing OpenVPN..."
apt-get install openvpn -y
cd /etc/openvpn || exit
wget https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip
apt-get install ca-certificates -y
apt-get install unzip -y
unzip ovpn.zip
rm ovpn.zip
echo

echo "Installing Python3 and dependencies..."
apt-get install python3 -y
apt-get install yad -y
apt-get install pip
pip install urllib3
pip install helium
pip install selenium
pip install BeautifulSoup4
echo

echo "Configuring auth.."
cd $ORIGIN || exit
echo 'Go to: https://my.nordaccount.com/en/dashboard/nordvpn/ to take your Username and Password'
echo 'Username: '
read USERNAME 
echo $USERNAME > pass.txt
echo 'Password: '
read PASSWORD  
echo $PASSWORD >> pass.txt
echo

echo "Moving all to /usr/bin ..."
mv vpn /usr/bin
mv pass.txt /usr/bin
mv recommended.py /usr/bin
