#!/usr/bin/env bash

RECOMMENDED=$(python3 /usr/bin/recommended.py)
sudo openvpn --config /etc/openvpn/ovpn_tcp/${RECOMMENDED}.tcp.ovpn --auth-user-pass /usr/bin/pass.txt &
notify-send --app-name=nordvpn --icon=nordvpn "Connected to VPN at ${RECOMMENDED} with PID: $!"
