#!/usr/bin/env bash

RECOMMENDED=$(python3 /usr/bin/recommended.py)
if sudo openvpn --config /etc/openvpn/ovpn_tcp/${RECOMMENDED}.tcp.ovpn --auth-user-pass /usr/bin/pass.txt --daemon ; then
  notify-send --app-name=nordvpn --icon=nordvpn "Connected to VPN at ${RECOMMENDED}"
  yad --notification --command "sudo killall openvpn && sudo killall yad" --image=nordvpn & 
else 
  notify-send --app-name=nordvpn --icon=error "Whoops! Connection failed. Please try again."
fi
 
